### ISSUE TITLE
Inference.py error

### ISSUE THREAD

**Issue by adaamko** [WPoelman/ud-boxer#7]
Hello!

Great project, very excited to try it out.

I'm facing an issue when I try to run the inference.py script. I installed all the dependencies according to your README file. The **grew** library is also installed based on the instructions. Also all the tests seem to be running without an issue. 

When I run the script I'm getting the follownig error:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File " ~/ud-boxer/inference.py", line 121, in <module>
    main()
  File " ~/ud-boxer/inference.py", line 92, in main
    res = grew.run(ud_filepath)
  File " ~/ud-boxer/ud_boxer/grew_rewrite.py", line 50, in run
    grew_graph = grew.graph(str(conll_path))
  File " ~/miniconda3/envs/boxer/lib/python3.9/site-packages/grew/graph.py", line 67, in graph
    raise utils.GrewError({"function": "grew.graph", "data": data, "message":e.value})
grew.utils.GrewError:
--------------------------------------------------------------------------------
{
  "function": "grew.graph",
  "data": " ~/ud-boxer/result/en.ud.stanza.conll",
  "message": "command 'load_graph' not found"
}
--------------------------------------------------------------------------------
```

I've tried it out on both Ubuntu and MacOS. Do you maybe have an idea what might cause this issue?

Thank you in advance!

**Comment by adaamko** [comment]
Versions:
Python: 3.9.7
libgrew: 1.10.0
grew: 1.10.0
opam: 4.14.0

**Comment by WPoelman** [comment]
Hi, thank you for your message!

I went down a rabbit hole and encountered the same issue (load_graph command not found) when I updated all associated GREW libraries to the latest versions (the ocaml libraries and the python package). It appears GREW is not compatible anymore with the way it used to process graphs (see section 1.5 on this page: https://grew.fr/usage/python/). The 'old' method was to give it a path to a UD parse (conll format), GREW would then build it's own version from it and use that. That does not work anymore in the new version. Now it needs a specific json format. I tried to update to this new format, but unfortunately, that breaks a lot of UD-Boxer functionality.

I did find a solution that can use the old format:
1. Uninstall all GREW related ocaml libraries: `opam uninstall grew grewpy libcaml-grew`
2. Install these specific versions: `opam install grew.1.8.1 grewpy.1.8.0 libcaml-grew.1.9.2`
3. Run `eval $(opam env)`

I also pinned the python requirements, it's probably good to update those as well since I got a warning/error from Stanza, which also needed an update. These changes are added to the README and the requirements.

Please let me know if you run into any more issues!

**Comment by adaamko** [comment]
Thank you very much, with this setting I was able to make it run!
